<?php
// Set headers to allow CORS and specify JSON response
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json');

// Array of catgirl facts
$catgirlFacts = [
    "Catgirls have a secret love for stargazing, their eyes sparkling like the night sky!",
    "When a catgirl gets bored, she might start batting at invisible strings in the air.",
    "Some catgirls are known to collect shiny objects like coins or jewelry in a hidden stash.",
    "A catgirl's favorite place to nap is often in the sunniest spot in the room.",
    "If a catgirl suddenly disappears, she's probably hiding to play a game of hide-and-seek!",
    "Catgirls have a special dance they do when they’re about to pounce on something.",
    "It's rumored that catgirls can communicate with regular cats in their own secret language!",
    "Catgirls can fall asleep in the strangest positions, sometimes mid-stretch!",
    "When a catgirl is really happy, she might give a little hop and a twirl.",
    "Catgirls sometimes meow in their sleep, dreaming of chasing butterflies.",
    "Some catgirls have a habit of kneading their pillows before settling in to sleep.",
    "When a catgirl is startled, her ears might flatten against her head.",
    "A catgirl’s purr is known to have calming effects on stressed-out friends.",
    "Catgirls have a sixth sense for knowing when a snack is being prepared nearby.",
    "If a catgirl likes you, she might nuzzle her head against your arm.",
    "Catgirls have been known to chase laser pointers just for fun!",
    "Sometimes, catgirls will hide their faces with their paws when they’re feeling shy.",
    "Catgirls love to sing, and you might catch one humming a little tune to herself.",
    "They often playfully bat at their own tails, like they’re surprised to find it there!",
    "Catgirls can be picky eaters, often turning up their noses at anything that’s not fish-flavored!",
    "If a catgirl is sleepy, she might curl up into a tiny ball, just like a kitten.",
    "Catgirls tend to be most active at night, just like their feline counterparts!",
    "Some catgirls have a secret collection of cute bows and accessories for their tails.",
    "Catgirls enjoy climbing to high places where they can oversee everything below.",
    "When a catgirl blushes, her ears sometimes turn pink, too!",
    "A catgirl's laugh sounds like a soft purr mixed with a giggle.",
    "Catgirls enjoy playing with balls of yarn, even if they try to act like they don’t!",
    "Sometimes, catgirls will mimic human expressions just to make people smile.",
    "Catgirls tend to have the softest, fluffiest tails you’ve ever seen!",
    "They can often be found napping in the most inconvenient spots, like laptop keyboards.",
    "Catgirls might playfully bat at your fingers if you’re typing too much.",
    "A catgirl will sometimes purr louder if she's extra comfy or being cuddled.",
    "If you give a catgirl a treat, she might give you a cute little 'mew' of thanks!",
    "Catgirls have an uncanny ability to know when you're feeling down and offer comfort.",
    "Their tails often twitch with excitement when they’re anticipating something fun!",
    "Some catgirls like to wear cute little hats that match their outfits!",
    "They have a habit of imitating other cats they meet, trying to out-cute them!",
    "Catgirls might get competitive during games, but they always play fair!",
    "They’re known to practice their meowing in front of mirrors to get it just right.",
    "Catgirls can sometimes sense when it's about to rain and will rush for cover.",
    "They have a natural grace that makes them excellent dancers, even in moonlight!",
    "Catgirls might tilt their heads to the side when they’re curious about something.",
    "They enjoy solving puzzles and challenges, especially if there’s a treat at the end!",
    "Catgirls love to bask in the sun and can be found lounging wherever it's warm.",
    "Their ears might wiggle if they're listening to their favorite song.",
    "Catgirls have a playful side that makes them great at telling funny stories!",
    "They enjoy playing with toy mice even more than the real thing.",
    "Sometimes, a catgirl will bring you a gift, like a flower or a shiny pebble.",
    "They have a habit of flicking their tails when they’re deep in thought.",
    "Catgirls are experts at making cozy nests with blankets and pillows!",
    "They can get mesmerized by the sight of fireflies glowing in the night.",
    "When a catgirl is embarrassed, she might cover her face with her paws.",
    "They adore playing hide-and-seek, often finding the best hiding spots!",
    "Catgirls might purr louder when it’s raining outside because it soothes them.",
    "They love watching birds outside the window and imagining themselves in flight!",
    "Catgirls sometimes have a knack for drawing cute doodles in the sand.",
    "If they see a butterfly, catgirls might try to chase it just for fun!",
    "They tend to give their friends cute nicknames that match their personalities.",
    "Catgirls might wiggle their noses if they smell something yummy in the air!",
    "They’re very particular about their favorite spots to sit and will defend them!",
    "Catgirls enjoy snuggling under soft blankets during cold weather.",
    "When a catgirl is shy, she might peek out from behind her fluffy tail.",
    "They enjoy collecting cute trinkets, especially ones shaped like stars!",
    "A catgirl’s laugh is often contagious, making everyone around smile.",
    "They might give you a little headbutt if they’re feeling especially fond of you!",
    "Catgirls often playfully swat at anything that dangles near them.",
    "They have a sweet tooth and will happily munch on anything sugary!",
    "Sometimes, they like to dance in the rain, splashing in puddles for fun.",
    "Catgirls can mimic the sounds of nature, like birds chirping or leaves rustling!",
    "They love bedtime stories and might even have a favorite fairy tale.",
    "A catgirl will sometimes sing lullabies to herself when she’s trying to sleep.",
    "They can sense when someone is nervous and might offer a comforting purr.",
    "If they hear a bell ring, catgirls might instinctively look around for its source.",
    "They adore sparkly things and might get distracted if they see something glimmering.",
    "Catgirls love to surprise their friends with spontaneous acts of kindness.",
    "They’re known to invent silly games just to make their friends laugh!",
    "Sometimes, they’ll wear little scarves to stay warm on chilly days.",
    "Catgirls might softly purr when they're around people they trust.",
    "They often dream about running through fields of flowers or chasing clouds.",
    "A catgirl's eyes can sparkle like stars when she’s feeling inspired!",
    "They have a natural talent for balancing on narrow ledges.",
    "Catgirls love bubble baths because they can play with all the bubbles!",
    "They enjoy painting their nails in bright, playful colors.",
    "Catgirls might sing in the shower, creating their own cute little concerts!",
    "They have a soft spot for anything that’s fluffy or furry!",
    "When a catgirl is really sleepy, she might start to purr louder without realizing it.",
    "They love collecting seashells and other treasures they find at the beach.",
    "Catgirls might be caught humming tunes that they made up on the spot.",
    "They enjoy playing with string lights, pretending they’re catching stars.",
    "Catgirls have a hidden talent for drawing cute little sketches of their friends.",
    "They sometimes bake sweet treats and share them with everyone around.",
    "When they’re really happy, catgirls might do a little wiggle dance!",
    "They’re always up for a game of tag, often being the fastest runner around!"
];

// Fetch a random catgirl fact
$randomFact = $catgirlFacts[array_rand($catgirlFacts)];

// Send the JSON response with the random fact
echo json_encode([
    "archetype" => "Catgirl",
    "fact" => $randomFact
]);