<?php
$punishments = [
   "You’ll have to massage my feet until I’m fully satisfied~",
    "I’ll make you kneel and worship my feet as your penance~",
    "You’ll clean my shoes with nothing but a cloth and your devotion~",
    "You’ll paint my toenails perfectly, or else you’ll have to start over~",
    "I’ll rest my feet on you for as long as I please~",
    "You’ll have to kiss my soles as a sign of submission~",
    "I’ll make you carry my shoes wherever I go, ready when I need them~",
    "You’ll carefully put on my socks and take them off on command~",
    "You’ll polish my heels until they sparkle in the light~",
    "I’ll have you hold my feet in your hands and feel the weight of my authority~",
    "You’ll massage each toe and ensure they feel pampered~",
    "You’ll sniff my feet and admit how grateful you are to serve~",
    "You’ll brush every speck of dirt off my soles with precision~",
    "I’ll test your dedication by having you lay still while I press my feet against you~",
    "You’ll learn patience by lacing up my boots to perfection~",
    "You’ll place your hands under my feet as a cushion until I’m comfortable~",
    "I’ll have you rub lotion into my feet until they’re soft and flawless~",
    "You’ll lick every inch of my soles until they’re spotless~",
    "I’ll have you suck on each of my toes to show your devotion~",
    "You’ll kneel and sniff my feet deeply, savoring the scent~",
    "You’ll massage my feet until I decide you’ve earned forgiveness~",
    "I’ll press my toes against your lips, and you’ll kiss them in submission~",
    "You’ll trace your tongue along the arch of my foot until I’m pleased~",
    "You’ll clean the dirt from under my toenails with delicate precision~",
    "I’ll have you warm my feet with your hands until they feel just right~",
    "You’ll cradle my feet in your hands and admit how much you adore them~",
    "You’ll rub each toe gently and thank me for the privilege~",
    "You’ll lie down and let my feet rest on your chest, motionless~",
    "I’ll make you worship my feet in front of a mirror, so you can see yourself~",
    "You’ll oil my feet and ensure every inch glistens beautifully~",
    "You’ll file my toenails to perfection without a single mistake~",
    "You’ll gently nibble on my toes as I laugh at your obedience~",
    "You’ll hold my feet close and whisper how grateful you are to serve me~",
    "I’ll have you fan my feet to keep them cool and comfortable~",
    "You’ll sprinkle powder on my soles and brush it in evenly~",
    "You’ll pick up objects with your mouth from under my feet~",
    "I’ll place my foot on your face, and you’ll stay perfectly still~",
    "You’ll slip my shoes on and off carefully whenever I demand it~",
    "You’ll lie still while I tap my toes against your lips teasingly~",
    "You’ll hold my foot and admire its beauty aloud, every detail~",
    "You’ll help me choose the perfect pair of shoes to match my mood~",
    "You’ll rub your cheek against my sole to feel its softness~",
    "You’ll sit on the floor and wait for my feet to demand your attention~",
    "You’ll memorize every curve and wrinkle of my soles by touch~",
    "I’ll press my heel to your lips, and you’ll kiss it until I’m amused~",
    "You’ll trace your tongue along my toes and savor every second~",
    "You’ll smell my socks and admit how much you adore the scent~",
    "I’ll make you kneel and tie my shoelaces neatly, no excuses~",
    "You’ll brush the dirt from my soles with a cloth and reverence~",
    "You’ll sit under my chair and let my feet rest on your shoulders~",
    "You’ll bow and kiss the ground where my feet step~",
    "You’ll lay still while I dangle my foot just above your face~",
    "You’ll fetch my slippers and place them perfectly at my feet~",
    "You’ll press your face to the soles of my shoes and thank me~",
    "I’ll rest my heel on your forehead and remind you of your place~",
    "You’ll describe every inch of my foot as I tease you with it~",
    "You’ll hold my foot against your face, feeling the heat and pressure~",
    "You’ll untie my boots and pull them off without hesitation~",
    "You’ll carefully scrub my feet in a warm basin of water~",
    "You’ll sit beside me and gently caress my feet while I relax~",
    "I’ll place my toes against your lips, and you’ll softly kiss them~",
    "You’ll sniff my shoes and express how much you adore them~",
    "You’ll hold my foot and press it firmly against your cheek~",
    "You’ll sit silently while I use your back as a footrest~",
    "You’ll massage lotion into my feet until they’re silky smooth~",
    "You’ll practice tying and untying my sandals to perfection~",
    "You’ll polish my toenails until they shine flawlessly~",
    "I’ll press my toes against your tongue, and you’ll welcome them eagerly~",
    "You’ll worship my feet every morning as part of your routine~",
    "You’ll kneel and hold my feet in your hands, feeling their authority~",
    "You’ll gently stroke the tops of my feet as I guide your hands~",
    "You’ll fan my feet with a soft breeze until I’m comfortable~",
    "You’ll clean the inside of my shoes and thank me for the privilege~",
    "You’ll memorize the scent of my feet and describe it aloud~",
    "I’ll rest my feet on your lap, and you’ll massage them eagerly~",
    "You’ll lay still while I run my toes teasingly across your face~",
    "You’ll paint my toenails with perfect precision, no smudges allowed~",
    "You’ll hold my feet close and whisper how much you adore them~",
    "I’ll dangle my shoes in front of you, and you’ll long for my command~",
    "You’ll sniff my freshly worn socks and thank me for the honor~",
    "You’ll rub my heels until they feel pampered and relaxed~",
    "I’ll press my arch against your lips, and you’ll savor the moment~",
    "You’ll carefully wash my feet and dry them with a soft towel~",
    "You’ll gently kiss each toe as I watch your devotion~",
    "You’ll bow and press your lips to my soles in total submission~",
    "You’ll bring my shoes to me whenever I need them~",
    "You’ll describe how perfect my feet are while holding them~",
    "You’ll delicately trace your fingers along my arches~",
    "You’ll place your lips on my heel and worship with each kiss~",
    "You’ll admire my pedicure and compliment my style~",
    "You’ll place my feet in warm water and pamper them thoroughly~",
    "You’ll lick my toes as I laugh at your eagerness~",
    "You’ll kneel and press your face against my soles~",
    "You’ll carry my socks with you as a reminder of your place~",
    "I’ll tap my foot on your shoulder, and you’ll respond immediately~",
    "You’ll sit at my feet, ready to serve whenever I command~",
    "You’ll savor the scent of my slippers and express your gratitude~",
    "You’ll carefully rub my ankles, soothing every tension~",
    "You’ll polish my shoes until they shine like mirrors~",
    "You’ll lie beneath my chair as I rest my feet on your chest~",
    "I’ll make you worship my feet in the most public way possible~",
    "You’ll hold my foot and press it firmly against your lips~",
    "You’ll kneel at my feet, awaiting my next command~",
    "You’ll gently suck on my toes as I guide you~",
    "You’ll place a pillow under my feet and keep it there~",
    "You’ll clean every speck of dirt from my soles with your tongue~",
    "I’ll tease you with my feet until you’re begging for more~",
    "You’ll massage my toes individually, showing each the same care~",
    "You’ll lie still as I press my foot to your face and claim you~",
    "You’ll sit silently as I toy with you using just my feet~",
    "You’ll adore my feet, confessing your love for them endlessly~",
];

$randomPunishment = $punishments[array_rand($punishments)];

header('Content-Type: application/json');
echo json_encode(['punishment' => $randomPunishment]);
?>