<?php
$punishments = [
    "You’ll be held upside down until you beg for mercy~",
    "I’ll tickle you until you can’t breathe from laughter~",
    "You’ll be kept in a cage until you learn your place~",
    "I’ll ignore you completely for a while~",
    "You’ll have to do my bidding as your punishment~",
    "I’ll make you watch as I toy with others~",
    "You’ll be reduced to nothing but a mere accessory~",
    "I’ll bind you and make you listen to my every command~",
    "You’ll have to serve as my footrest for an hour~",
    "I’ll blindfold you and leave you guessing my next move~",
    "You’ll be forced to recount your deepest fears~",
    "I’ll put you on display for everyone to see~",
    "You’ll spend time locked in a box, contemplating your actions~",
    "I’ll make you wear a collar as a constant reminder of your place~",
    "You’ll have to beg for my attention~",
    "I’ll tease you relentlessly without giving in~",
    "You’ll be made to clean my lair as punishment~",
    "I’ll make you recite my praises over and over~",
    "You’ll be subjected to my whims without any say~",
    "I’ll keep you in the dark until you’re ready to submit~",
    "You’ll serve as a warning to others~",
    "I’ll make you listen to my laughter while you suffer~",
    "You’ll have to endure being watched by others~",
    "I’ll use you as a demonstration for my power~",
    "You’ll be silenced until you learn your lesson~",
    "I’ll keep you in a tight grip, reminding you of my strength~",
    "You’ll have to hold a heavy object above your head until you break~",
    "I’ll toy with your mind until you can’t think straight~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll hold you in my palm and remind you of your size~",
    "You’ll be made to repeat your mistakes until you understand~",
    "I’ll put you in a position where you can’t escape~",
    "You’ll have to endure my breath on your neck~",
    "I’ll challenge you to outsmart me, knowing you’ll fail~",
    "You’ll be blindfolded and made to guess my moves~",
    "I’ll make you endure the humiliation of being my toy~",
    "You’ll be left alone in darkness, waiting for my return~",
    "I’ll use your own words against you until you submit~",
    "You’ll be put in a position where you must rely on me~",
    "I’ll turn the tables and make you my servant~",
    "You’ll be bound and helpless as I decide your fate~",
    "I’ll challenge you to escape my grip~",
    "You’ll have to wear a sign of your failure~",
    "I’ll make you wait for my command, teasing your anticipation~",
    "You’ll have to endure the weight of my presence on your chest~",
    "I’ll remind you of your insignificance in every way~",
    "You’ll have to recount your dreams only to find them out of reach~",
    "I’ll make you experience my power firsthand~",
    "You’ll have to serve me tea while kneeling~",
    "I’ll use your weaknesses against you until you break~",
    "You’ll be forced to admit your deepest secrets~",
    "I’ll make you feel small in every way possible~",
    "You’ll be placed in a position where you can’t escape~",
    "I’ll keep you at my feet, knowing you can’t resist~",
    "You’ll be subjected to my whims without a say in the matter~",
    "I’ll challenge you to complete impossible tasks for my amusement~",
    "You’ll have to endure the pressure of my dominance~",
    "I’ll keep you close enough to feel my power~",
    "You’ll be made to perform menial tasks as my servant~",
    "I’ll toy with your mind until you’re left confused~",
    "You’ll be required to recite a mantra of submission~",
    "I’ll hold you tightly until you understand my control~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you wear a blindfold as I toy with you~",
    "You’ll be subjected to the weight of my presence~",
    "I’ll remind you of your place with every glance~",
    "You’ll be forced to wear a collar as a sign of your status~",
    "I’ll leave you in a room full of distractions~",
    "You’ll have to keep still as I observe you~",
    "I’ll make you experience the thrill of being hunted~",
    "You’ll be required to endure my playful torment~",
    "I’ll put you in a position where you must beg~",
    "You’ll be left to ponder your mistakes in solitude~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my every whim without question~",
    "I’ll keep you guessing about my next move~",
    "You’ll be held close, reminding you of my dominance~",
    "I’ll make you confess your feelings to me~",
    "You’ll have to bear the weight of my decisions~",
    "I’ll toy with your mind until you’re lost in submission~",
    "You’ll face the consequences of your choices without mercy~",
    "I’ll remind you of your place in every interaction~",
    "You’ll be subjected to my playful dominance~",
    "I’ll challenge you to resist my charm~",
    "You’ll have to endure my teasing until you break~",
    "I’ll keep you under my thumb until you understand~",
    "You’ll be put in a position where you must serve~",
    "I’ll hold you accountable for your actions~",
    "You’ll have to endure the humiliation of my presence~",
    "I’ll remind you of your size and powerlessness~",
    "You’ll be required to complete tasks to prove your worth~",
    "I’ll keep you guessing about my next move~",
    "You’ll be forced to acknowledge your place~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll be put in a position where you must obey~",
    "I’ll challenge you to prove your worth to me~",
        "You’ll be made to walk on your knees until I say otherwise~",
    "I’ll have you whisper my name over and over as your punishment~",
    "You’ll spend an hour locked in a cage, contemplating your choices~",
    "I’ll have you wear a blindfold as I tease you mercilessly~",
    "You’ll serve as my footstool while I relax~",
    "I’ll make you recount your misdeeds while I listen~",
    "You’ll be held firmly as a reminder of my strength~",
    "I’ll make you experience the weight of your mistakes~",
    "You’ll have to kiss the ground I walk on~",
    "I’ll ignore your pleas until you learn your lesson~",
    "You’ll be made to beg for a mere glance from me~",
    "I’ll keep you tied up and vulnerable~",
    "You’ll face the embarrassment of being on display~",
    "I’ll tease you until you’re breathless with desire~",
    "You’ll be forced to watch as I enjoy my power~",
    "I’ll make you wear a sign of your submission~",
    "You’ll have to answer my questions or face the consequences~",
    "I’ll remind you of your size with every touch~",
    "You’ll be left in darkness, waiting for my return~",
    "I’ll force you to recall your deepest secrets until you break~",
    "You’ll be bound to a chair, helpless as I toy with you~",
    "I’ll make you complete tasks to earn my affection~",
    "You’ll endure my laughter as I toy with your fate~",
    "I’ll leave you wanting as I walk away~",
    "You’ll serve me drinks while I sit comfortably~",
    "I’ll make you admit your wrongdoings publicly~",
    "You’ll have to wear a collar that symbolizes your place~",
    "I’ll tease you until you can’t resist any longer~",
    "You’ll face the consequences of your defiance without mercy~",
    "I’ll make you write lines about your submission~",
    "You’ll be subjected to my whims without hesitation~",
    "I’ll keep you guessing as I toy with your mind~",
    "You’ll have to complete impossible challenges for my amusement~",
    "I’ll make you feel small with every glance~",
    "You’ll be forced to endure my presence for hours~",
    "I’ll hold you close, reminding you of my dominance~",
    "You’ll be put in a position where you must serve~",
    "I’ll keep you tied up, unable to resist my commands~",
    "You’ll have to listen to my commands without question~",
    "I’ll remind you of your place with every action~",
    "You’ll face the consequences of your rebellion~",
    "I’ll make you wear my mark as a reminder~",
    "You’ll be forced to acknowledge your submission to me~",
    "I’ll make you beg for my attention~",
    "You’ll serve as my plaything until I tire of you~",
    "I’ll tease you relentlessly until you can’t take it anymore~",
    "You’ll have to endure my playful torment~",
    "I’ll remind you of your size with every touch~",
    "You’ll be made to recite my praises repeatedly~",
    "I’ll toy with your emotions until you’re completely entranced~",
    "You’ll be held captive by my presence~",
    "I’ll keep you in a vulnerable position for my amusement~",
    "You’ll be required to submit to my every whim~",
    "I’ll make you wait until I decide you’ve learned your lesson~",
    "You’ll have to face the consequences of your mistakes~",
    "I’ll hold you in my grasp, reminding you of your insignificance~",
    "You’ll have to whisper sweet nothings to me as punishment~",
    "I’ll keep you guessing about my next move~",
    "You’ll be bound until you plead for freedom~",
    "I’ll toy with your mind until you’re lost in submission~",
    "You’ll have to acknowledge your place with every action~",
    "I’ll make you experience the thrill of being hunted~",
    "You’ll be kept in suspense as I decide your fate~",
    "I’ll remind you of my power with every command~",
    "You’ll have to endure the weight of my gaze~",
    "I’ll make you confess your deepest desires~",
    "You’ll face the consequences of your disobedience~",
    "I’ll keep you on edge until I decide your fate~",
    "You’ll be put in a position where you must please me~",
    "I’ll make you wait until I’m satisfied~",
    "You’ll be required to cater to my every need~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll serve as my reminder of what happens to the disobedient~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions with no mercy~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll be made to endure my teasing until you submit~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll have to endure my playful dominance~",
    "I’ll keep you under my thumb until you understand~",
    "You’ll be put in a position where you must obey~",
    "I’ll make you face the weight of my presence~",
    "You’ll be subjected to my whims without question~",
    "I’ll toy with your mind until you can’t resist~",
    "You’ll face the consequences of your choices without mercy~",
    "I’ll remind you of your place with every interaction~",
    "You’ll have to beg for forgiveness until I’m satisfied~",
    "I’ll make you serve as my personal assistant until further notice~",
    "You’ll be left in suspense, awaiting my next move~",
    "I’ll have you read my commands aloud as punishment~",
    "You’ll spend time in isolation to reflect on your actions~",
    "I’ll force you to wear a tag that symbolizes your submission~",
    "You’ll have to endure my laughter while you suffer~",
    "I’ll make you confess your failures to me repeatedly~",
    "You’ll be kept in the dark, waiting for my return~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to endure being my toy until I’m satisfied~",
    "I’ll keep you bound until you plead for release~",
    "You’ll serve as my reminder of what happens to the defiant~",
    "I’ll tease you relentlessly until you break~",
    "You’ll be forced to face the consequences of your disobedience~",
    "I’ll hold you tightly, reminding you of my control~",
    "You’ll have to beg for my affection as punishment~",
    "I’ll keep you guessing about my next move~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll be made to endure my playful torment~",
    "I’ll keep you under my control until you understand~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll remind you of your place with every action~",
    "You’ll be forced to endure my presence until I’m satisfied~",
    "I’ll keep you guessing as I toy with your mind~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll make you feel small with every glance~",
    "You’ll be subjected to my whims without hesitation~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll be put in a position where you must serve~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll be forced to wear my mark as a reminder~",
    "I’ll make you wait until I’m satisfied with your submission~",
    "You’ll have to endure the weight of my presence~",
    "I’ll challenge you to prove your worth~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness~",
    "You’ll face the consequences of your defiance~",
    "I’ll keep you on edge until I decide your fate~",
    "You’ll have to endure my teasing until you can’t resist~",
    "I’ll remind you of your place with every action~",
    "You’ll have to recite my praises repeatedly as punishment~",
    "I’ll toy with your emotions until you’re completely entranced~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll make you wear a collar that symbolizes your place~",
    "You’ll have to serve as my reminder of what happens to the disobedient~",
    "I’ll toy with your mind until you can’t think straight~",
    "You’ll have to acknowledge your submission with every word~",
    "I’ll keep you guessing about my next move~",
    "You’ll be forced to endure my presence until I’m satisfied~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll toy with your mind until you’re completely at my mercy~",
    "You’ll face the consequences of your actions with no escape~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll challenge you to prove your worth~",
    "You’ll have to endure being my toy until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be made to confess your failures to me repeatedly~",
    "I’ll keep you guessing about my next move~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll toy with your emotions until you’re completely lost~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll make you recite my praises until you break~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be made to serve me without question~",
    "I’ll remind you of your place until you can’t take it anymore~",
    "You’ll have to endure the weight of my gaze~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll face the consequences of your choices without mercy~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll have to beg for forgiveness until I’m satisfied~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll serve as my plaything until I tire of you~",
    "I’ll tease you until you’re breathless with desire~",
    "You’ll be forced to endure my laughter while you suffer~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll face the consequences of your actions with no escape~",
    "I’ll toy with your mind until you’re completely at my mercy~",
    "You’ll be made to serve as my personal assistant~",
    "I’ll keep you guessing until you can’t think straight~",
    "You’ll face the weight of my presence until you submit~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll make you confess your deepest fears~",
    "You’ll be subjected to my whims without question~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until you submit~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll have to beg for my affection as punishment~",
    "I’ll toy with your emotions until you’re completely lost~",
    "You’ll face the weight of my gaze until you can’t resist~",
    "I’ll make you wear a collar that symbolizes your submission~",
    "You’ll serve as my reminder of what happens to the disobedient~",
    "I’ll toy with your mind until you can’t think straight~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~",
    "I’ll remind you of your insignificance with every command~",
    "You’ll have to serve me drinks while I relax~",
    "I’ll challenge you to prove your worth~",
    "You’ll be subjected to my whims until I’m satisfied~",
    "I’ll remind you of your place as my subordinate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you kiss the ground I walk on~",
    "You’ll endure the weight of my presence until you submit~",
    "I’ll toy with your emotions until you’re completely under my spell~",
    "You’ll have to acknowledge your submission until I’m satisfied~",
    "I’ll remind you of your place with every command~",
    "You’ll be forced to wear a tag that symbolizes your submission~",
    "I’ll keep you guessing as I toy with your fate~",
    "You’ll face the consequences of your actions until I’m satisfied~",
    "I’ll make you confess your deepest fears until you break~",
    "You’ll have to serve as my reminder of what happens to the defiant~",
    "I’ll remind you of your insignificance in every way possible~",
    "You’ll face the weight of my gaze until you submit~",
    "I’ll keep you guessing about my next move~",
    "You’ll have to endure my teasing until you can’t resist any longer~",
    "I’ll challenge you to prove your worth to me~",
    "You’ll be forced to listen to my commands without question~",
    "I’ll remind you of your size and powerlessness until you break~",
    "You’ll face the consequences of your defiance~",
    "I’ll make you kiss the ground I walk on as punishment~",
    "You’ll endure the weight of my gaze until you submit~",
    "I’ll toy with your mind until you can’t resist any longer~",
    "You’ll be forced to endure my teasing until you submit~",
    "I’ll keep you guessing until I’m satisfied~",
    "You’ll face the consequences of your actions without mercy~"
];

$randomPunishment = $punishments[array_rand($punishments)];

header('Content-Type: application/json');
echo json_encode(['punishment' => $randomPunishment]);
?>