<?php
$environments = [
    "a serene beach with gentle waves lapping at the shore~",
    "an empty street lit by flickering streetlights~",
    "a tranquil forest glade filled with soft sunlight~",
    "a vast, open field under a clear blue sky~",
    "a quiet mountain trail leading to stunning views~",
    "an abandoned warehouse echoing with silence~",
    "a desolate parking lot at night, illuminated by the moon~",
    "a peaceful meadow dotted with wildflowers~",
    "a foggy valley where everything feels mysterious~",
    "a deserted pier stretching into the calm sea~",
    "a hidden garden surrounded by tall hedges~",
    "an empty train station, echoing with memories~",
    "a long, winding path through a dense thicket~",
    "a still lake reflecting the clouds above~",
    "a narrow canyon with towering cliffs on either side~",
    "a rocky shoreline where the waves crash dramatically~",
    "an expansive desert with rippling sand dunes~",
    "an old, creaky bridge over a quiet river~",
    "a snow-covered landscape, silent and pristine~",
    "a tranquil pond with lily pads floating peacefully~",
    "a secluded cave with shimmering stalactites~",
    "an overgrown path through a dense forest~",
    "a deserted hillside overlooking the horizon~",
    "a misty coast where the fog rolls in off the ocean~",
    "a quiet library filled with dust-covered books~",
    "a small, empty cabin in the woods~",
    "an abandoned gas station on a forgotten highway~",
    "a winding river cutting through a lush valley~",
    "an empty boardwalk, creaking with every step~",
    "a hidden alcove beneath a waterfall~",
    "an old castle ruin surrounded by thick foliage~",
    "a sunlit balcony overlooking a serene vista~",
    "a rocky cliffside where the ocean crashes below~",
    "a misty moor with soft, heather-covered hills~",
    "an ancient stone circle, weathered by time~",
    "a forgotten orchard, trees heavy with fruit~",
    "a deserted farmhouse, overgrown with vines~",
    "a peaceful hilltop with a view of rolling hills~",
    "a moonlit beach where the sand sparkles~",
    "an empty sports field, echoing with silence~",
    "a dilapidated train yard, tracks rusting away~",
    "a secluded waterfall cascading into a crystal pool~",
    "a long, quiet road lined with autumn trees~",
    "a tiny island surrounded by turquoise waters~",
    "a vast tundra, snow-covered and silent~",
    "an empty amusement park, rides creaking in the wind~",
    "a darkened tunnel leading into the unknown~",
    "a grand old theater, dust swirling in the air~",
    "an abandoned observatory on a hill~",
    "a still swamp, fog rolling over the water~",
    "a lonely lighthouse standing against the sea~",
    "an ancient ruin overrun by nature~",
    "a quiet bay where the water is still~",
    "a secluded mountain pass, silent and serene~",
    "a long-abandoned fishing village, boats left to rot~",
    "a tranquil rock garden with raked gravel~",
    "an empty tennis court, surrounded by overgrown grass~",
    "a dark forest with towering trees and little light~",
    "a vast, empty canyon with colorful rock formations~",
    "a secluded beach with soft, white sand~",
    "a rusted Ferris wheel standing tall in silence~",
    "an expansive rice field, golden and ripe for harvest~",
    "a crumbling stone wall in an empty field~",
    "an unlit, narrow alley between old brick buildings~",
    "a vibrant coral reef under clear waters~",
    "an abandoned quarry, deep and echoing~",
    "a long, winding riverbank with tall grasses~",
    "a serene snowy village, lights twinkling in the distance~",
    "a quiet hilltop graveyard, stones weathered by time~",
    "a remote lighthouse on a rocky outcrop~",
    "a hidden lagoon surrounded by cliffs~",
    "a dusty road stretching into the horizon~",
    "a lush bamboo forest, whispering in the wind~",
    "a foggy marsh where shadows play tricks~",
    "an isolated mountain summit with a panoramic view~",
    "a hidden beach accessible only by a narrow path~",
    "an ancient battlefield overgrown with grass~",
    "a quaint picnic area, empty and inviting~",
    "a stone bridge covered in moss~",
    "a soft, sandy desert with gentle winds~",
    "a ruined castle surrounded by wildflowers~",
    "a quiet garden with a trickling fountain~",
    "an empty greenhouse, plants growing wild~",
    "an old, twisted tree standing alone~",
    "a narrow ledge overlooking a steep drop~",
    "an expansive farmland with rolling hills~",
    "a forgotten barn, wood creaking in the breeze~",
    "a sunken garden where nature has taken over~",
    "a small island in the middle of a lake~",
    "a narrow path through a colorful flower field~",
    "a misty ridge where the land meets the clouds~",
    "a hidden grotto with sparkling waters~",
    "a wide-open plain stretching as far as the eye can see~",
    "a secluded rock formation perfect for exploration~",
    "an overgrown pathway leading to a forgotten place~",
    "a quiet inlet surrounded by towering cliffs~",
    "a deserted road winding through the countryside~",
    "a serene backyard garden filled with colorful blooms~",
    "a rustic mountain lodge, empty and waiting for guests~",
    "a narrow path through a golden wheat field~",
    "an old stone tower standing tall against the sky~",
    "a small fishing cove with abandoned boats~",
    "an expansive landscape with rolling hills and valleys~",
    "a tranquil glen where the sound of water can be heard~",
    "a quiet nature reserve, alive with sounds of wildlife~",
    "a vast tundra with distant mountains on the horizon~"
];

// Select a random environment
$randomEnvironment = $environments[array_rand($environments)];

header('Content-Type: application/json');
echo json_encode(['environment' => $randomEnvironment]);
?>
