<?php
$punishments = [
    "You’ll file my sharp, pointy toenails to perfection until they gleam with precision~",
    "I’ll press my sharp toenails against your skin, leaving faint trails as a reminder of your place~",
    "You’ll polish my razor-sharp toenails until they shine like deadly jewels~",
    "You’ll kneel and admire how perfectly my sharp nails curve, whispering your praises~",
    "I’ll drag my pointy toenails teasingly across your back, sending chills down your spine~",
    "You’ll trace the edges of my sharp toenails with your tongue, careful not to falter~",
    "I’ll tap my sharp toenails against your lips, daring you to show your devotion~",
    "You’ll sit still as I dangle my foot over you, my claws glinting ominously~",
    "I’ll rest my foot on you, letting the weight of my sharp toenails remind you who’s in charge~",
    "You’ll hold my feet gently, ensuring my sharp toenails remain flawless and untouched~",
    "I’ll rake my sharp toenails lightly down your chest, leaving a thrilling mark of my authority~",
    "You’ll massage my feet, careful to avoid the deadly tips of my sharp toenails~",
    "I’ll toy with you by pressing my clawed toes just against your neck, leaving you breathless~",
    "You’ll carefully paint my sharp toenails, ensuring no smudges mar their perfection~",
    "I’ll press the point of my toenail against your cheek, reminding you of your fragility~",
    "You’ll admire the curve and sharpness of my nails, confessing how much they terrify and excite you~",
    "I’ll dangle my foot over you, letting the sharp tips of my claws hover just out of reach~",
    "You’ll gently clean under my sharp toenails, showing how dedicated you are to serving~",
    "I’ll rake my sharp claws across the floor, the sound sending shivers down your spine~",
    "You’ll thank me for allowing you to feel the weight of my sharp toenails pressed against you~",
    "I’ll rest my foot on your hand, letting my sharp nails dig in just enough to make you squirm~",
    "You’ll gaze at my toenails, marveling at how sharp and powerful they are~",
    "I’ll leave faint marks on your skin with my sharp toenails, a symbol of my control~",
    "You’ll buff my claws until they’re sharp and smooth, worthy of admiration~",
    "I’ll toy with you, scratching the surface of your skin with the very tips of my claws~",
    "You’ll confess how much you adore my sharp toenails as you kneel at my feet~",
    "I’ll press my claws against the back of your neck, making you shiver with anticipation~",
    "You’ll softly blow on my sharp toenails to dry the polish perfectly~",
    "I’ll dangle my sharp claws near your lips, teasing you with the danger~",
    "You’ll massage my feet while I test the sharpness of my claws against your arm~",
    "I’ll drag my toenails across your clothes, threatening to tear through~",
    "You’ll hold my foot steady as I press my sharp claws into your palm~",
    "I’ll carve faint patterns on your skin with my claws, each mark a symbol of your submission~",
    "You’ll practice filing my toenails perfectly, sharpening them to my satisfaction~",
    "I’ll toy with you, lightly scratching my name onto your skin with my nails~",
    "You’ll admit how intimidating and captivating my sharp toenails are as you serve me~",
    "I’ll rest my foot on your face, my claws grazing your cheek teasingly~",
    "You’ll trace each sharp toenail with your finger, marveling at their beauty and danger~",
    "I’ll lightly drag my claws across your lips, daring you to flinch~",
    "You’ll clean every speck of dust from under my sharp toenails without hesitation~",
    "I’ll leave a faint line down your back with one of my claws, a mark of my control~",
    "You’ll hold still as I test the sharpness of my claws against your fingertips~",
    "I’ll hover my foot over you, the sharp tips of my toenails casting a shadow on your face~",
    "You’ll thank me for allowing my sharp toenails to grace your skin, even lightly~",
    "I’ll remind you of your place by pressing my clawed toes against your wrist~",
    "You’ll shiver as I trace my sharp claws along the edge of your collar~",
    "You’ll learn patience by cleaning each of my sharp toenails meticulously~",
    "I’ll toy with you, letting my claws scrape against the edge of your jaw~",
    "You’ll delicately hold my foot as I flex my sharp nails in front of your face~",
    "I’ll leave a playful yet menacing trail of scratches on your arm with my toenails~",
    "You’ll confess how much you admire my sharp toenails while filing them to perfection~",
    "I’ll press my sharp nails against your shoulder, letting their weight remind you of your place~",
    "You’ll adore the precision and beauty of my sharp toenails as I make you worship them~",
    "I’ll tap my claws against the floor, the sound commanding your attention~",
    "You’ll carefully buff and polish my sharp claws until they shine brilliantly~",
    "I’ll toy with you by raking my sharp nails across the edge of your ear~",
    "You’ll sit at my feet, memorizing the curve and sharpness of each claw~",
    "I’ll scratch your palm lightly with my toenails, leaving you trembling with excitement~",
    "You’ll gently kiss each sharp claw, showing your devotion to their perfection~",
    "I’ll let my claws hover above your skin, teasing you with the threat of a scratch~",
    "You’ll thank me for every mark my sharp toenails leave on your skin~",
    "I’ll press my claws into your hand, reminding you of how fragile you are beneath me~",
    "You’ll rub my feet, always mindful of the sharp tips of my nails~",
    "I’ll dangle my foot near your lips, the sharp toenails demanding your attention~",
    "You’ll sit quietly as I run my claws along your arm, marking my territory~",
    "I’ll carve playful patterns into your skin with my claws, leaving you marked as mine~",
    "You’ll softly breathe on my claws, admiring their sharp elegance~",
    "I’ll rest my foot on your chest, letting my claws dig in just enough to keep you still~",
    "You’ll polish each claw to a mirror-like shine, ensuring their flawless appearance~",
    "I’ll toy with you, scratching faint lines along your collarbone with my nails~",
    "You’ll admit how much my sharp toenails excite and intimidate you~",
    "I’ll place my foot on your leg, my claws grazing your skin deliberately~",
    "You’ll carefully ensure my toenails remain sharp and flawless with every filing~",
    "I’ll trace my claws along your jawline, making you tremble with submission~",
    "You’ll worship my sharp toenails, confessing your admiration for their beauty~",
    "I’ll drag my claws lightly across your lips, testing your obedience~",
    "You’ll clean my sharp toenails with utter focus, knowing any mistake could cost you~",
    "I’ll toy with you, pressing my claws against the softest parts of your skin~",
    "You’ll kneel and polish each sharp toenail until they shine brilliantly~",
    "I’ll rake my claws teasingly down your side, making you shiver at the touch~",
    "You’ll admit how lucky you are to serve someone with such powerful claws~",
    "I’ll let my claws hover near your throat, reminding you of your vulnerability~",
    "You’ll marvel at the sharpness of my nails as I press them lightly against your hand~",
    "I’ll run my claws down your back slowly, leaving a thrilling trail~",
    "You’ll hold my feet gently, ensuring my claws remain immaculate and threatening~",
    "I’ll press my sharp toenails into the ground, the sound commanding your focus~",
    "You’ll thank me for every scratch I leave on your skin, a symbol of your devotion~",
];

$randomPunishment = $punishments[array_rand($punishments)];

header('Content-Type: application/json');
echo json_encode(['punishment' => $randomPunishment]);
?>